# Generated by Django 5.0.6 on 2025-02-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('enterprise_value', models.FloatField(blank=True, null=True)),
                ('earnings_yield', models.FloatField(blank=True, null=True)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_payout_ratio', models.FloatField(blank=True, null=True)),
                ('avg_volume', models.BigIntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('year_revenue_growth', models.FloatField(blank=True, null=True)),
                ('price_perchng_1mon', models.FloatField(blank=True, null=True)),
                ('price_perchng_1year', models.FloatField(blank=True, null=True)),
                ('price_perchng_3mon', models.FloatField(blank=True, null=True)),
                ('price_perchng_3year', models.FloatField(blank=True, null=True)),
                ('price_perchng_5year', models.FloatField(blank=True, null=True)),
                ('roce', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
