# Generated by Django 5.1.6 on 2025-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nifty50GraphHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time_range', models.CharField(choices=[('1M', '1 Month'), ('6M', '6 Months'), ('1Y', '1 Year'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('10Y', '10 Years')], max_length=5)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date', 'time_range')},
            },
        ),
    ]
