# Generated by Django 5.1.6 on 2025-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockDetail', '0002_nifty50dailyhistory_nifty50monthlyhistory_and_more'),
        ('StockDetail', '0002_nifty50graphhistory'),
    ]

    operations = [
    ]
