# Generated by Django 5.1.6 on 2025-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockDetail', '0003_merge_20250325_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSE_500_Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('earnings_yield', models.FloatField(blank=True, null=True)),
                ('dividend_payout_ratio', models.FloatField(blank=True, null=True)),
                ('avg_volume', models.FloatField(blank=True, null=True)),
                ('exchange', models.CharField(default='BSE', max_length=10)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('price_perchng_1mon', models.FloatField(blank=True, null=True)),
                ('price_perchng_3mon', models.FloatField(blank=True, null=True)),
                ('price_perchng_1year', models.FloatField(blank=True, null=True)),
                ('price_perchng_3year', models.FloatField(blank=True, null=True)),
                ('price_perchng_5year', models.FloatField(blank=True, null=True)),
                ('roce', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Nifty50DailyHistory',
        ),
        migrations.DeleteModel(
            name='Nifty50MonthlyHistory',
        ),
        migrations.DeleteModel(
            name='Nifty50TimeRangeSummary',
        ),
    ]
