# Generated by Django 5.1.6 on 2025-03-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockDetail', '0004_bse_500_stocks_delete_nifty50dailyhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bse_500_stocks',
            name='roce',
        ),
    ]
