# Generated by Django 5.1.6 on 2025-04-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockDetail', '0006_bse500graphhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('share_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('reserve_and_surplus', models.CharField(blank=True, max_length=100, null=True)),
                ('minority_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('non_current_liabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('current_liabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('total_liabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_assets', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_work_in_progress', models.CharField(blank=True, max_length=100, null=True)),
                ('investments', models.CharField(blank=True, max_length=100, null=True)),
                ('other_assets', models.CharField(blank=True, max_length=100, null=True)),
                ('total_assets', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockDetail.company')),
            ],
        ),
    ]
